#!/bin/bash
source ${0%/*}/config.sh

echo 1、创建脚本${nginx_install}/sbin/cut_nginx_log.sh
cat <<EOF > ${nginx_install}/sbin/cut_nginx_log.sh
#!/bin/bash
# This script run at 00:00

# The Nginx logs path
logs_path="${nginx_install}/logs/"

mkdir -p \${logs_path}\$(date -d "yesterday" +"%Y")/\$(date -d "yesterday" +"%m")/
mv \${logs_path}access.log \${logs_path}\$(date -d "yesterday" +"%Y")/\$(date -d "yesterday" +"%m")/access_\$(date -d "yesterday" +"%Y%m%d").log
kill -USR1 \`cat ${nginx_install}/nginx.pid\`
EOF
