#!/bin/bash
if [[ -z $included ]]; then
    run_date=$(date +%Y-%m-%d-%H%M%S)

    wd=$(dirname $(readlink -f $0))
    swd=$(cd $wd/../ && pwd)

    bin_dir=$swd/bin
    cache_dir=$swd/archives
    tpl_dir=$swd/templates

    log_dir=$swd/log
    build_dir=$swd/build

    # 安装日志
    install_log=$log_dir/install.log

    source ${0%/*}/functions.sh
    source ${0%/*}/config.sh
    xcheck "读取配置文件成功" $?

    [ ! -d $build_dir ] && mkdir -p $build_dir
    [ ! -d $log_dir ] && mkdir -p $log_dir

    [ ! -d $srv_bin ] && mkdir -p $srv_bin
    [ ! -d $srv_etc ] && mkdir -p $srv_etc
    [ ! -d $srv_log ] && mkdir -p $srv_log
    [ ! -d $srv_cache ] && mkdir -p $srv_cache
    [ ! -d $srv_data ] && mkdir -p $srv_data

    included=True
fi
[[ -n $1 ]] && file=$1 || file=all
file=$bin_dir/install_$file.sh
source $file
xcheck "$file 运行" $?
